trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Step 1: SDK Install (Solved ✅)
- task: UseDotNet@2
  displayName: 'Force Install .NET SDK 10'
  inputs:
    packageType: 'sdk'
    version: '10.0.201'
    includePreviewVersions: true

# Step 2: Build (Warnings Bypass Command Added)
- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) -p:NuGetAudit=false -p:TreatWarningsAsErrors=false'

# Step 3: Publish & Zip (Warnings Bypass Command Added)
- task: DotNetCoreCLI@2
  displayName: 'Publish & Zip the API'
  inputs:
    command: 'publish'
    publishWebProjects: true 
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -p:NuGetAudit=false -p:TreatWarningsAsErrors=false'
    zipAfterPublish: true

# Step 4: Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Save the Package (Artifact)'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop' 
    publishLocation: 'Container'